services:
  - type: web
    name: modichat-api
    env: node
    buildCommand: "npm run build"
    startCommand: "npm start"
    envVars:
      - key: MONGO_URI
        sync_env_var: true
      - key: JWT_SECRET
        sync_env_var: true
      - key: NODE_ENV
        value: production
