services:
  - type: web
    name: modichat-api
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://thelordrishabh:8uNkCQmkQTYp2ysH@cluster0.s57qasv.mongodb.net/social-app?appName=Cluster0
      - key: JWT_SECRET
        value: supersecretkey_changethis_tomethinglong123
      - key: PORT
        value: 10000
